// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsufpuzlavxodhwklulr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdWZwdXpsYXZ4b2Rod2tsdWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDU2ODUsImV4cCI6MjA2NTQ4MTY4NX0.el5YIPhoE_yMLQ4AiGaFbCyfeCQnomuDEBL3VqcvfUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);